### ISSUE TITLE
Add Version Tracking with uv and pyproject.toml

### ISSUE THREAD

**Issue by BastianSpatz** [BastianSpatz/Chess#2]
Example code to set up version tracking using uv:

```toml
[tool.uv]
version = "0.1.0"
[project]
name = "simplistic_chess"
version = "0.1.0"
dependencies = ["pygame"]
```

This ensures consistent dependency management.
